package com.ddmwsst.helloworld;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-01-22T20:15:57.440-07:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://ddmwsst.com/helloworld", name = "HelloWorld")
@XmlSeeAlso({com.ddmwsst.helloworld.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HelloWorld {

    @WebResult(name = "helloResponse", targetNamespace = "http://ddmwsst.com/helloworld/types", partName = "out")
    @WebMethod
    public com.ddmwsst.helloworld.types.HelloResponse sayHello(
        @WebParam(partName = "in", name = "helloRequest", targetNamespace = "http://ddmwsst.com/helloworld/types")
        com.ddmwsst.helloworld.types.HelloRequest in
    );
}
