package com.ddmwsst.helloworld;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-01-22T20:02:17.664-07:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "HelloWorld", 
                  wsdlLocation = "./wsdl/HelloWorld.wsdl",
                  targetNamespace = "http://ddmwsst.com/helloworld") 
public class HelloWorld_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ddmwsst.com/helloworld", "HelloWorld");
    public final static QName SoapPort = new QName("http://ddmwsst.com/helloworld", "SoapPort");
    static {
        URL url = null;
        try {
            url = new URL("./wsdl/HelloWorld.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWorld_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "./wsdl/HelloWorld.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWorld_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorld_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorld_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "SoapPort")
    public HelloWorld getSoapPort() {
        return super.getPort(SoapPort, HelloWorld.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "SoapPort")
    public HelloWorld getSoapPort(WebServiceFeature... features) {
        return super.getPort(SoapPort, HelloWorld.class, features);
    }

}
