
package com.ddmwsst.helloworld;

import javax.xml.ws.Endpoint;

import server.HelloWorldImpl;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-01-22T20:02:17.651-07:00
 * Generated source version: 2.5.1
 * 
 */
 
public class HelloWorld_SoapPort_Server{

    protected HelloWorld_SoapPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloWorldImpl();
        String address = "http://localhost:8080/helloworld/HelloWorld";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new HelloWorld_SoapPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
